# Generated by Django 4.1.5 on 2023-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_myuser_delete_user_alter_exercise_exercise_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="username",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="email address"),
        ),
    ]
