# Generated by Django 4.1.5 on 2023-01-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_myuser_username_alter_myuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="email address"),
                ),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="MyUser",),
    ]
