# Generated by Django 4.1.5 on 2023-01-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_delete_myuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=11, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
