# Generated by Django 4.1.5 on 2023-01-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_exercise_id_for_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="MyUser",),
        migrations.DeleteModel(name="Room",),
        migrations.AlterField(
            model_name="exercise",
            name="id_for_user",
            field=models.IntegerField(default=1),
        ),
    ]
