# Generated by Django 4.1.5 on 2023-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_myuser_delete_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fb_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
