# Generated by Django 4.1.5 on 2023-05-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_myuser_fb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fb_access_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='fb_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
