# Generated by Django 4.1.5 on 2023-05-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_myuser_fb_access_token_alter_myuser_fb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
