# Generated by Django 4.1.5 on 2023-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_exercise_date_alter_weightentry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
